export const TASK_CREATE = "TASK_CREATE";
export const TASK_RESOLVED = "TASK_RESOLVED";
export const TASK_REMOVE = "TASK_REMOVE";

export const TASKS_LOADING = "TASKS_LOADING";
export const TASKS_RETRIVED = "TASKS_RETRIVED";
export const TASKS_ERROR = "TASKS_ERROR";
